#
# List the Databases and its status
#
SELECT NAME, OPEN_MODE, CONTROLFILE_TYPE FROM V$DATABASE;

#
#
#

ALTER DATABASE CLOSE;

SELECT OPEN_MODE FROM V$DATABASE;

ALTER DATABASE DISMOUNT;

SELECT OPEN_MODE FROM V$DATABASE;


ALTER DATABASE ADD LOGFILE GROUP 6 ('/home/oracle/hsjd/log/redo3a.log', '/home/oracle/hsjd/log/redo3b.log') SIZE 100M;

SELECT TABLESPACE_NAME, FILE_NAME FROM SYS.DBA_DATA_FILES;
SELECT TABLESPACE_NAME, FILE_NAME, ONLINE_STATUS, STATUS FROM SYS.DBA_DATA_FILES  WHERE TABLESPACE_NAME='ATNC_CRRD_TS1_URG';

ALTER TABLESPACE ATNC_CRRD_TS1_URG OFFLINE NORMAL;
ALTER TABLESPACE ATNC_CRRD_TS1_URG ONLINE;

