#
# List the Databases and its status
#
SELECT NAME, OPEN_MODE, CONTROLFILE_TYPE FROM V$DATABASE;

#
#
#

ALTER DATABASE CLOSE;

SELECT OPEN_MODE FROM V$DATABASE;

ALTER DATABASE DISMOUNT;

SELECT OPEN_MODE FROM V$DATABASE;


ALTER DATABASE ADD LOGFILE GROUP 6 ('/home/oracle/hsjd/log/redo3a.log', '/home/oracle/hsjd/log/redo3b.log') SIZE 100M;